### ISSUE TITLE
Add a background illustration to the "learn-easy" page relevant to the website

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#13]

**Comment by zain-mansuri** [comment]
@Harshita248 in scrum1.ejs page wants to add background image same as login image "imglogin.jpg" ?
assign task to me

**Comment by Harshita248** [comment]
@Zain7867 Wait for sometime. We will start as soon as we get the list of all the participants and then will assign it to you.

**Comment by Harshita248** [comment]
@Zain7867 are you a participant of SLoP for this particular project?
As this issue is under SLoP

**Comment by fatmab2809** [comment]
Hi, which background illustration do you want to add to the page? Do you want us to look for some good ones online?

**Comment by Harshita248** [comment]
Yes you can go for online illustrations which suits best @fatmab2809

**Comment by fatmab2809** [comment]
Ok, I will look for a few and share the images here, for you to choose. Is that okay?

**Comment by imHarry404** [comment]
I want to contribute on this issue

**Comment by imHarry404** [comment]
I want to contribute on this issue

**Comment by imHarry404** [comment]
I want to contribute to this issue

**Comment by himanshu007-creator** [comment]
please assign me this issue.

**Comment by fatmab2809** [comment]
> Yes you can go for online illustrations which suits best @fatmab2809

Please assign me the issue.

**Comment by Aniket118** [comment]
Please, assign this issue to me.

**Comment by Harshita248** [comment]
It's already assigned and done @Aniket118
