### ISSUE TITLE
Add some good illustrations to the images folder (relevant to the website) to be used in the website .

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#16]
Please refer to trello.com

**Comment by shashwats538** [comment]
Hey @Harshita248 . I'd like to work on this. #16

**Comment by Harshita248** [comment]
okay @shashwats538 please go ahead but it should be relevant to the project.

**Comment by shashwats538** [comment]
@Harshita248 . Please check PR #23

**Comment by shashwats538** [comment]
Hey @Harshita248 , Please Check PR #24 .
