### ISSUE TITLE
Add a good illustration in the background of "sign in" page and make a box or form type "sign in" enhancing the buttons.

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#18]
![Learn Easy - Google Chrome 10_3_2020 11_22_58 PM](https://user-images.githubusercontent.com/46245859/94998457-886ac580-05cf-11eb-995c-fe82848534c1.png)

**Comment by shashwats538** [comment]
Hey @Harshita248 . Assign this issue to me. I'll redesign this page. #18

**Comment by Harshita248** [comment]
Okay sure @shashwats538
