### ISSUE TITLE
Add animation effects on hovering the buttons on sign in page and change the styling.

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#19]

**Comment by nikldev0** [comment]
Hi! Could I try working on this?

**Comment by Harshita248** [comment]
Hey @nikldev0 are you a participant under SLoP open source program as this issue is under SLoP so this will only be assigned to those participants under SLoP'20.

**Comment by nikldev0** [comment]
Unfortunately not, is this open for members of the public to join?

**Comment by Harshita248** [comment]
Sorry but this is labelled as SLoP so only participants can contribute. It's not public @nikldev0

**Comment by UMuktesh** [comment]
Can I take up the work?

**Comment by Harshita248** [comment]
Yes sure @UMuktesh go ahead!!
