### ISSUE TITLE
Add similar styling to both the login page as well as the index page.

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#22]
Styling in the sense the illustration in the background and the header and footer

**Comment by UMuktesh** [comment]
@Harshita248 check PR #31

**Comment by Harshita248** [comment]
please provide the screenshots for the same @UMuktesh

**Comment by UMuktesh** [comment]
![image](https://user-images.githubusercontent.com/63556122/95816769-7dd1ce00-0d3d-11eb-9a23-4e250b5d763a.png)
![image](https://user-images.githubusercontent.com/63556122/95816780-862a0900-0d3d-11eb-9e36-62492ef5ba0c.png)

**Comment by Harshita248** [comment]
See to the issue, the points are for designing the index page in the similar way so please do that and again make the pr then only I can allocate the points
