### ISSUE TITLE
Decrease the width of the navbar, change the hover colour of the menu items in the navbar, make the page intact by reducing the size of illustration and login form( particularly by removing scrollbar in Desktop view and making it compact )

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#32]
Additional : Remove text-decoration : underline in "Login Here"

**Comment by UMuktesh** [comment]
Can I take up the work?

**Comment by Harshita248** [comment]
Yes go ahead @UMuktesh  make it responsive as the login part on the right should not appear above the image for smaller size screen ..it should appear below it
