### ISSUE TITLE
Add a sign up page similar to the signin (index) page for both student and admin where the data of the user is to be stored in a database.

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#33]
the signup button should have a dropdown for student and admin and the dropdown menu will redirect to the signup page for the student as well as the admin . (These separate pages can be styled similar or as per your choice).

**The data of student and admin when signup or login should be stored in a database respectively.**
_Please add screenshots for the same._

**Comment by shashwats538** [comment]
Hey @Harshita248 . Can you assign this to me please?
#33

**Comment by Harshita248** [comment]
yes for sure go ahead @shashwats538
