### ISSUE TITLE
Add a loader while redirecting to index page, learn easy as well as check easy page. Also add similar navbar as index page to both the pages.

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#35]
Add an appealing loader or loading page to the website with sticky navbar.

**Please provide screenshots of the same.**

**Comment by UMuktesh** [comment]
Can I take up the work?

**Comment by Harshita248** [comment]
Go ahead @UMuktesh  please see to it that the loader is relevant to the website and looks good and implement it on mentioned pages . Also add a screenshot when done
