### ISSUE TITLE
Style the columns with animation effects , add content and various section, provide the title (all in learn easy) to give it a single page website look.

### ISSUE THREAD

**Issue by Harshita248** [Harshita248/Scrum-Management#36]
Add animation effects to the different sections such as how to use , why this , suggest an idea for the title and add it accordingly after the addition of carousel and footer in a different issue. Please refer trello.com
This issue will take time while adding different sections such as about , usage , etc in a single page. A feature such as light theme and dark mode scroll button can be added to make the website look attractive. 

**Please add screenshots for the same.**

**Comment by imHarry404** [comment]
@Harshita248  I want to contribute to under SWoC. I know CSS and JS better and I can do this.

**Comment by Harshita248** [comment]
Okay go ahead @ami-harry

**Comment by vismitap** [comment]
May I work on this issue?

**Comment by Harshita248** [comment]
Yes sure @vismitap

**Comment by vismitap** [comment]
@Harshita248 Please explain what needs to be done here in a bit detail. Which page are you talking about?

**Comment by Harshita248** [comment]
The page in which there are different columns ...

**Comment by vismitap** [comment]
> The page in which there are different columns ...

Do you mean this? 
![image](https://user-images.githubusercontent.com/47056243/108059724-ef1ee600-707b-11eb-9c14-95750b7eccc1.png)
What animations do you want on this page. I am sorry, I didn't get it 😥 
Other pages are registration pages, so not sure which page you are talking about. 😥

**Comment by vismitap** [comment]
Please tell me what needs to be done here. The text boxes are not center-aligned, I can fix that. What kind of animation is required here?

**Comment by Harshita248** [comment]
You need to give animation to the whole page like fadein or fadeout and also to the columns such that they appear seconds after one another. Also add carousel and footer

**Comment by vismitap** [comment]
Hey! Please put difficulty level label here!
