### ISSUE TITLE
Create GitHub Pages

### ISSUE THREAD

**Issue by Akshu-on-github** [Harshita248/Scrum-Management#48]
As GitHub hosts static pages for free, creating a GitHub pages site would allow people to preview the project before contributing

**Comment by jyotsana3108** [comment]
I would like to contribute to this issue under SWOC. Can you please assign it to me?

**Comment by Harshita248** [comment]
Sure @jyotsana3108

**Comment by vismitap** [comment]
Hey! May I work on this?
