### ISSUE TITLE
Login Page for Admin and Student confined in single box to make it look clean

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#67]
Login Page for Student and Admin will be confined in a single Event and Box by using the JavaScript Effects to make it look like a Toggle effect... And Hide  the Overflow of the Portal.

**Comment by Harshita248** [comment]
Okay great @imsachinsingh10

**Comment by imsachinsingh10** [comment]
This Issue has been resolved please close this issue

**Comment by Harshita248** [comment]
Done
