### ISSUE TITLE
Merging the Admin Registration Page and Student Page and it can be accessed from same page

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#68]

**Comment by Harshita248** [comment]
Okay

**Comment by imsachinsingh10** [comment]
Ma'am this will take a bit more effort to complete... so if you can then label it as "Medium"

**Comment by imsachinsingh10** [comment]
Please close this issue I have resolved and fixed the bug which was mentioned by other participant Today (4th Feb 2021)

**Comment by Harshita248** [comment]
Done
