### ISSUE TITLE
Details on fetch_details.ejs page is not visible 

### ISSUE THREAD

**Issue by vismitap** [Harshita248/Scrum-Management#76]
**Describe the bug**
----
The table and header is not visible because of the background image.

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to 'http://localhost:3000/details'
  2. View the page
  
**Expected behavior**
-----
The contents of page should be easily visible.

**Possible solution**
----
Removing the dark background image would do and the white background also match the theme of landing page.

**Screenshots**
Now:
![image](https://user-images.githubusercontent.com/47056243/107147612-fd327f80-6974-11eb-9c7e-8d49d4ebadfc.png)
After Updating:
![image](https://user-images.githubusercontent.com/47056243/107147738-ac6f5680-6975-11eb-9451-5e14cd24c81a.png)

Please assign this issue to me! I will fix it and move to the other issue!

**Comment by Harshita248** [comment]
Okay

**Comment by vismitap** [comment]
Please add the difficulty tag as well. ✌
