### ISSUE TITLE
Auto Hiding Navbar which reduces the issues of overlapping when scrolling 

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#78]
**Is your feature request related to a problem? Please describe.**
----
- No, it is not, it is just an added extra feature for the website

**Describe the solution you'd like**
----
- Whenever website will be scrolled down then Navbar will automatically hide itself.

**Describe alternatives you've considered**
----
- There is no need of that

**Additional context**
----
- NA.

**Comment by imsachinsingh10** [comment]
Ma'am Please Label this and other 4 issues as well, if you think it is required

**Comment by imsachinsingh10** [comment]
Please Assign me this issue, also please close this issue because it has been resolved

**Comment by imsachinsingh10** [comment]
Please Close this is Issue, it has been resolved

**Comment by Harshita248** [comment]
Done
