### ISSUE TITLE
Scroll to Top Button

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#79]
**Is your feature request related to a problem? Please describe.**
----
- No it is an extra added benefit for the users.

**Describe the solution you'd like**
----
- When website will be scrolled to a certain extent then this button will appear which will take the user to the top of the website

**Describe alternatives you've considered**
----
- No need of that.

**Additional context**
----
- NA

**Comment by imsachinsingh10** [comment]
Please Assign this issue to me. I have already made this only thing is left to make a PR

**Comment by Harshita248** [comment]
Done
