### ISSUE TITLE
Contact Section

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#80]
**Is your feature request related to a problem? Please describe.**
----
- Every Commercial website should have a contact section where all the details are given. Also user can ask for queries also.

**Describe the solution you'd like**
----
- NA

**Describe alternatives you've considered**
----
- NA

**Additional context**
----
- NA

**Comment by imsachinsingh10** [comment]
If you think then label it as a Medium Level problem under SWOC

**Comment by imsachinsingh10** [comment]
Please Close this is Issue, it has been resolved

**Comment by Harshita248** [comment]
Done
