### ISSUE TITLE
Navbar Hamburg Button Not Working in the Media Queries

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#81]
**Describe the bug**
----
- For Mobile users Navbar Hamburg not working

**To Reproduce**
----
- Steps to reproduce the behavior:
    1. 
  
**Expected behavior**
-----
- It should respond when it is clicked

**Possible solution**
----
- JavaScript Function fix has to be done

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it.

**Comment by imsachinsingh10** [comment]
If Bugs are considered under SWoC then please label it under SWoC

**Comment by Harshita248** [comment]
Done
