### ISSUE TITLE
Smooth Scroll Feature

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#82]
**Is your feature request related to a problem? Please describe.**
----
- No, it is a added feature

**Describe the solution you'd like**
----
- Whenever few navbar tabs are clicked and if it is on the same page then it will scroll down smoothly to that portion

**Describe alternatives you've considered**
----
- NA

**Additional context**
----
- NA

**Comment by imsachinsingh10** [comment]
Please Assign me this issue, also please accept the PR to this issue

**Comment by Harshita248** [comment]
Done
