### ISSUE TITLE
Sidebar Widget (Floating)

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#87]
**Is your feature request related to a problem? No.**
----
- A clear and concise description of what the problem is. On the right hand side of the website there will be a floating widget to all the social media links of SCRUM page

**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by imsachinsingh10** [comment]
Please Assign this issue to me and close all the previous issue

**Comment by imsachinsingh10** [comment]
This issue has been resolved, please close this issue

**Comment by Harshita248** [comment]
Done
