### ISSUE TITLE
The title needs to be rearranged in RegAdmin page to make it look nicer

### ISSUE THREAD

**Issue by vismitap** [Harshita248/Scrum-Management#89]
**Describe the bug**
----
- A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/47056243/108061600-90a73700-707e-11eb-9a93-500713041b54.png)
![image](https://user-images.githubusercontent.com/47056243/108061811-d9f78680-707e-11eb-95a9-0ada23d03d79.png)

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to 'http://localhost:3000/regadm'
  2. See error

I can fx this issue! Please assign me as a part of SWoC 😀

**Comment by Harshita248** [comment]
Okay

**Comment by vismitap** [comment]
Please add the difficulty level
