### ISSUE TITLE
Fetch_details page is broken

### ISSUE THREAD

**Issue by vismitap** [Harshita248/Scrum-Management#90]
**Describe the bug**
----
- A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/47056243/108062195-74f06080-707f-11eb-8be6-50f5e06e7e25.png)

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to 'http://localhost:3000/fetch_details'
  2. See error

**Expected behavior**
-----
- A clear and concise description of what you expected to happen.
-A Table should be shown containing the details

I can fix this issue! Please assign me! ✌

**Comment by Harshita248** [comment]
Sure please fix this if you can

**Comment by vismitap** [comment]
Please add the SWoC and difficulty level labels ! ✨
