### ISSUE TITLE
Accessing the Chatfuel to create a chatbot for website

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#95]
**Is your feature request related to a problem? Please describe.**
`NA`
----
- A clear and concise description of what the problem is. 
- It will create a Chatbot which will respond to user accordingly
- Also, it will be connected with Facebook messenger
**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by imsachinsingh10** [comment]
Please assign this to me as Easy or Medium, whatever you think is relevant

**Comment by imsachinsingh10** [comment]
@Harshita248 this ISSUE has been resolved

**Comment by Harshita248** [comment]
Done
