### ISSUE TITLE
Making the Chatbot in codebase of SCRUM

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#96]
**Is your feature request related to a problem? Please describe.**
`NA`
----
- A clear and concise description of what the problem is. 
- It will make Chatbot functional on website apart from connecting it with the Messenger 

**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by imsachinsingh10** [comment]
Please, assign this to me as Hard label under SWoC21,

**Comment by imsachinsingh10** [comment]
@Harshita248 this issue has been resolved

**Comment by Harshita248** [comment]
Done
