### ISSUE TITLE
Making Teams Webpage of SCRUM

### ISSUE THREAD

**Issue by imsachinsingh10** [Harshita248/Scrum-Management#97]
**Is your feature request related to a problem? Please describe.**
`NA`
----
- A clear and concise description of what the problem is. 
- A clear description of People working in SCRUM need to be made
**Describe the solution you'd like**
----
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by imsachinsingh10** [comment]
@Harshita248 Please assign this to me, and will be creating a complete new webpage for this Teams section

**Comment by Harshita248** [comment]
ok

**Comment by imsachinsingh10** [comment]
This issue has been resolved

**Comment by Harshita248** [comment]
Done
